version: '3.8'

services:
  elasticsearch:
    image: elastic/elasticsearch:8.17.7
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - backend_net

volumes:
  esdata:

networks:
  backend_net:
